import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '../components/Header/header'
import Footer from '../components/Footer/footer'
import { ThemeProvider } from './theme-provider'
import { ReactNode } from 'react'

import '@fortawesome/fontawesome-svg-core/styles.css'

import { config } from '@fortawesome/fontawesome-svg-core'
// Tell Font Awesome to skip adding the CSS automatically
// since it's already imported above
config.autoAddCss = false

import dotenv from 'dotenv'
dotenv.config()

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'TunesBlend',
    // description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode // Define the type of the children prop
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <div className={inter.className}>
                        <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-800 py-1 px-2">
                            <Header title="TunesBlend" />
                            <main className="w-[100vw] flex-grow">
                                {children}
                            </main>
                            <Footer />
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}

export default RootLayout
function userRouter() {
    throw new Error('Function not implemented.')
}
