import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '../components/Header/header'
import Footer from '../components/Footer/footer'
import { ThemeProvider } from './theme-provider'
import { ThemeToggle } from '../components/ThemeToggle/ThemeToggle'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'TunesBlend',
    // description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode // Define the type of the children prop
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (
        <html lang="en">
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <div className={inter.className}>
                        <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-800">
                            <Header title="TunesBlend" />
                            <main className="flex-grow flex justify-center items-center">
                                {children}
                            </main>
                            <Footer />
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}

export default RootLayout
